-- ============================================================================
-- Family Tree app — seed data
-- Generated from the verified family-tree-preview.html data block. Run this
-- AFTER schema.sql, once, in the Supabase SQL Editor. Safe to re-run: it
-- upserts everything by id.
-- ============================================================================

-- ---------- abubakar : people ----------
insert into people (id, family, name, gender, gen, title, traits, unknown, is_user) values
  ('abubakar_aisha', 'abubakar', 'Aisha', 'f', 1, null, null, false, false),
  ('abubakar_father_of_hamidah', 'abubakar', 'Father of Hamidah', 'm', 1, null, null, true, false),
  ('abubakar_halim', 'abubakar', 'Halim', 'm', 1, null, null, false, false),
  ('abubakar_jakinah', 'abubakar', 'Jakinah', 'f', 1, null, 'Passed away.', false, false),
  ('abubakar_kamaludeen', 'abubakar', 'Kamaludeen', 'm', 1, null, 'Ran Kasab Kadai alongside his brother Osman.', false, false),
  ('abubakar_menatchia', 'abubakar', 'Menatchia', 'f', 1, null, null, false, false),
  ('abubakar_mother_of_hamidah', 'abubakar', 'Mother of Hamidah', 'f', 1, null, null, true, false),
  ('abubakar_osman', 'abubakar', 'Osman', 'm', 1, null, 'Took over the Kasab Kadai butchery in Little India.', false, false),
  ('abubakar_sarbudeen', 'abubakar', 'Sarbudeen', 'm', 1, null, 'Halimah Ummal''s 1st husband.', false, false),
  ('abubakar_abu_bakar', 'abubakar', 'Abu Bakar', 'm', 2, 'Patriarch', 'Born in Madurai; moved to Neravy in the 1930s. Entrepreneur and philanthropist — founded Kasab Kadai, Singapore''s first halal butchery to import Australian meat and introduce the meat mincer, and built the Neravy clock tower in 1958.', false, false),
  ('abubakar_abu_salee', 'abubakar', 'Abu Salee', 'm', 2, null, 'Deceased.', false, false),
  ('abubakar_aisha_d_of_menatchia', 'abubakar', 'Aisha (d. of Menatchia)', 'f', 2, null, null, false, false),
  ('abubakar_ali_saburi', 'abubakar', 'Ali Saburi', 'm', 2, null, null, false, false),
  ('abubakar_dawood', 'abubakar', 'Dawood', 'm', 2, null, null, false, false),
  ('abubakar_hamidah', 'abubakar', 'Hamidah', 'f', 2, null, 'Abu Bakar''s wife. Raised six children in Neravy.', false, false),
  ('abubakar_jahir_hussain', 'abubakar', 'Jahir Hussain', 'm', 2, null, null, false, false),
  ('abubakar_mannan', 'abubakar', 'Mannan', 'm', 2, null, null, false, false),
  ('abubakar_mumtaj_begam', 'abubakar', 'Mumtaj Begam', 'f', 2, null, null, false, false),
  ('abubakar_nasar', 'abubakar', 'Nasar', 'm', 2, null, null, false, false),
  ('abubakar_nisha', 'abubakar', 'Nisha', 'f', 2, null, null, false, false),
  ('abubakar_nurjahan', 'abubakar', 'Nurjahan', 'f', 2, null, null, false, false),
  ('abubakar_partner_of_abu_bakar', 'abubakar', 'Partner of Abu Bakar', 'f', 2, null, null, true, false),
  ('abubakar_siti', 'abubakar', 'Siti', 'f', 2, null, null, false, false),
  ('abubakar_zubaidah', 'abubakar', 'Zubaidah', 'f', 2, null, null, false, false),
  ('abubakar_abdul_kader', 'abubakar', 'Abdul Kader', 'm', 3, '“Kadai Appa”', 'Halimah Ummal''s 2nd husband, from the Kuddus family. Ran a provision shop and hawker stalls; passed away.', false, false),
  ('abubakar_abdul_salam', 'abubakar', 'Abdul Salam', 'm', 3, null, null, false, false),
  ('abubakar_ashraf', 'abubakar', 'Ashraf', 'm', 3, null, null, false, false),
  ('abubakar_asina_begam', 'abubakar', 'Asina Begam', 'f', 3, null, 'A very clean and organised individual.', false, false),
  ('abubakar_farah', 'abubakar', 'Farah', 'f', 3, null, null, false, false),
  ('abubakar_partner_of_farah', 'abubakar', 'Partner of Farah', 'm', 3, null, null, true, false),
  ('abubakar_gani_maricar', 'abubakar', 'Gani Maricar', 'm', 3, null, 'From the Maricar family — one of several marriages linking the two clans.', false, false),
  ('abubakar_halimah_ummal', 'abubakar', 'Halimah Ummal', 'f', 3, null, 'Shared her father''s intelligence and determined spirit.', false, false),
  ('abubakar_harsharth', 'abubakar', 'Harsharth', 'm', 3, null, null, false, false),
  ('abubakar_irfan', 'abubakar', 'Irfan', 'm', 3, null, null, false, false),
  ('abubakar_partner_of_irfan', 'abubakar', 'Partner of Irfan', 'f', 3, null, null, true, false),
  ('abubakar_jainalabuden', 'abubakar', 'Jainalabuden', 'm', 3, null, null, false, false),
  ('abubakar_maimoon', 'abubakar', 'Maimoon', 'f', 3, 'aka Muthaji', 'Remarried twice; her descendants run through two very different branches.', false, false),
  ('abubakar_partner_of_jainalabuden', 'abubakar', 'Partner of Jainalabuden', 'f', 3, null, null, true, false),
  ('abubakar_abdul_razak', 'abubakar', 'Abdul Razak', 'm', 4, null, null, false, false),
  ('abubakar_aminah_banu', 'abubakar', 'Aminah Banu', 'f', 4, null, null, false, false),
  ('abubakar_dawood_sultan', 'abubakar', 'Dawood Sultan', 'm', 4, null, null, false, false),
  ('abubakar_faridah', 'abubakar', 'Faridah', 'f', 4, null, null, false, false),
  ('abubakar_harris', 'abubakar', 'Harris', 'm', 4, null, null, false, false),
  ('abubakar_hussain', 'abubakar', 'Hussain', 'm', 4, null, null, false, false),
  ('abubakar_iqbal', 'abubakar', 'Iqbal', 'm', 4, null, null, false, false),
  ('abubakar_jainabu_natchia', 'abubakar', 'Jainabu Natchia', 'f', 4, null, null, false, false),
  ('abubakar_jegaber_natchial', 'abubakar', 'Jegaber Natchial', 'f', 4, null, 'From the Maricar & Abu Bakar family — married Khalibullah, from the Abu Bakar & Kuddus family.', false, false),
  ('abubakar_khalibullah', 'abubakar', 'Khalibullah', 'm', 4, null, null, false, false),
  ('abubakar_khalid', 'abubakar', 'Khalid', 'm', 4, null, null, false, false),
  ('abubakar_mamudha', 'abubakar', 'Mamudha', 'f', 4, null, null, false, false),
  ('abubakar_nur_nisha', 'abubakar', 'Nur Nisha', 'f', 4, null, null, false, false),
  ('abubakar_rafiq', 'abubakar', 'Rafiq', 'm', 4, null, null, false, false),
  ('abubakar_rahima_begam', 'abubakar', 'Rahima Begam', 'f', 4, null, null, false, false),
  ('abubakar_salim', 'abubakar', 'Salim', 'm', 4, null, null, false, false),
  ('abubakar_samsunihar_aachama', 'abubakar', 'Samsunihar Aachama', 'f', 4, null, 'Knitter and self-taught makeup artist — dressed the brides of Neravy for decades, including her own step-sister''s wedding.', false, false),
  ('abubakar_syed_janira_banu', 'abubakar', 'Syed Janira Banu', 'f', 4, null, null, false, false),
  ('abubakar_taj_mohammad', 'abubakar', 'Taj Mohammad', 'm', 4, null, null, false, false),
  ('abubakar_ummu_salimah', 'abubakar', 'Ummu Salimah', 'f', 4, null, null, false, false),
  ('abubakar_yacob', 'abubakar', 'Yacob', 'm', 4, null, null, false, false),
  ('abubakar_affrin_nisha', 'abubakar', 'Affrin Nisha', 'f', 5, null, null, false, false),
  ('abubakar_ansari', 'abubakar', 'Ansari', 'm', 5, null, null, false, false),
  ('abubakar_ayisha_raihana', 'abubakar', 'Ayisha Raihana', 'f', 5, null, null, false, false),
  ('abubakar_badhusha_raja', 'abubakar', 'Badhusha Raja', 'm', 5, null, null, false, false),
  ('abubakar_child_of_yacob', 'abubakar', 'Child of Yacob', 'u', 5, null, null, true, false),
  ('abubakar_diwan', 'abubakar', 'Diwan', 'm', 5, null, null, false, false),
  ('abubakar_faherah_begam', 'abubakar', 'Faherah Begam', 'f', 5, null, 'Compiled this family archive — the reason this dashboard exists.', false, true),
  ('abubakar_faizal', 'abubakar', 'Faizal', 'm', 5, null, null, false, false),
  ('abubakar_fajurullah', 'abubakar', 'Fajurullah', 'm', 5, null, null, false, false),
  ('abubakar_farhana_begam', 'abubakar', 'Farhana Begam', 'f', 5, null, null, false, false),
  ('abubakar_farisha_begam', 'abubakar', 'Farisha Begam', 'f', 5, null, null, false, false),
  ('abubakar_farveen_banu', 'abubakar', 'Farveen Banu', 'f', 5, null, null, false, false),
  ('abubakar_fauziah', 'abubakar', 'Fauziah', 'f', 5, null, null, false, false),
  ('abubakar_haziqah', 'abubakar', 'Haziqah', 'f', 5, null, null, false, false),
  ('abubakar_mohamad_nabeel', 'abubakar', 'Mohamad Nabeel', 'm', 5, null, null, false, false),
  ('abubakar_mohamad_nadeem', 'abubakar', 'Mohamad Nadeem', 'm', 5, null, null, false, false),
  ('abubakar_mohammad_farshith', 'abubakar', 'Mohammad Farshith', 'm', 5, null, null, false, false),
  ('abubakar_mohammad_ridzwan', 'abubakar', 'Mohammad Ridzwan', 'm', 5, null, null, false, false),
  ('abubakar_muhammad_farhan', 'abubakar', 'Muhammad Farhan', 'm', 5, null, null, false, false),
  ('abubakar_nasir_shah', 'abubakar', 'Nasir Shah', 'm', 5, null, null, false, false),
  ('abubakar_nisar', 'abubakar', 'Nisar', 'm', 5, null, null, false, false),
  ('abubakar_riffeth_begam', 'abubakar', 'Riffeth Begam', 'f', 5, null, null, false, false),
  ('abubakar_riyaz', 'abubakar', 'Riyaz', 'm', 5, null, null, false, false),
  ('abubakar_shireen_halimah', 'abubakar', 'Shireen Halimah', 'f', 5, null, null, false, false),
  ('abubakar_sibling_of_child_of_yacob', 'abubakar', 'Sibling of Child of Yacob', 'u', 5, null, null, true, false),
  ('abubakar_sibling_of_sibling_of_child_of_yacob', 'abubakar', 'Sibling of Sibling of Child of Yacob', 'u', 5, null, null, true, false),
  ('abubakar_thahmilla', 'abubakar', 'Thahmilla', 'f', 5, null, null, false, false),
  ('abubakar_thameem', 'abubakar', 'Thameem', 'm', 5, null, 'Faherah''s fiancé.', false, false),
  ('abubakar_wassim_shah', 'abubakar', 'Wassim Shah', 'm', 5, null, null, false, false),
  ('abubakar_yassar', 'abubakar', 'Yassar', 'm', 5, null, null, false, false),
  ('abubakar_aadhil', 'abubakar', 'Aadhil', 'm', 6, null, null, false, false),
  ('abubakar_child_of_mohammad', 'abubakar', 'Child of Mohammad', 'u', 6, null, null, true, false),
  ('abubakar_ibrahim_fashith', 'abubakar', 'Ibrahim Fashith', 'm', 6, null, null, false, false),
  ('abubakar_khaira', 'abubakar', 'Khaira', 'f', 6, null, null, false, false),
  ('abubakar_muhammad', 'abubakar', 'Muhammad Fawaz Khwaja', 'm', 6, null, null, false, false),
  ('abubakar_muhammad_fauz_khwaja', 'abubakar', 'Muhammad Fauz Khwaja', 'm', 6, null, null, false, false),
  ('abubakar_nafeelah', 'abubakar', 'Nafeelah', 'f', 6, null, null, false, false),
  ('abubakar_shireen', 'abubakar', 'Shireen', 'f', 6, null, null, false, false),
  ('abubakar_zayan_emir_shah', 'abubakar', 'Zayan Emir Shah', 'm', 6, null, null, false, false)
on conflict (id) do update set
  family = excluded.family, name = excluded.name, gender = excluded.gender, gen = excluded.gen,
  title = excluded.title, traits = excluded.traits, unknown = excluded.unknown, is_user = excluded.is_user,
  updated_at = now();

-- ---------- abubakar : unions ----------
insert into unions (id, family, partner1_id, partner2_id, note) values
  ('abubakar_u1', 'abubakar', 'abubakar_aisha', 'abubakar_osman', null),
  ('abubakar_u2', 'abubakar', 'abubakar_menatchia', 'abubakar_kamaludeen', null),
  ('abubakar_u3', 'abubakar', 'abubakar_jahir_hussain', 'abubakar_siti', null),
  ('abubakar_u4', 'abubakar', 'abubakar_irfan', 'abubakar_partner_of_irfan', null),
  ('abubakar_u5', 'abubakar', 'abubakar_farah', 'abubakar_partner_of_farah', null),
  ('abubakar_u6', 'abubakar', 'abubakar_aisha_d_of_menatchia', 'abubakar_mannan', null),
  ('abubakar_u7', 'abubakar', 'abubakar_jakinah', 'abubakar_halim', null),
  ('abubakar_u8', 'abubakar', 'abubakar_jakinah', 'abubakar_sarbudeen', null),
  ('abubakar_u9', 'abubakar', 'abubakar_mother_of_hamidah', 'abubakar_father_of_hamidah', null),
  ('abubakar_u10', 'abubakar', 'abubakar_hamidah', 'abubakar_abu_bakar', 'Hamidah and Abu Bakar are the founding couple of the Abu Bakar line.'),
  ('abubakar_u11', 'abubakar', 'abubakar_halimah_ummal', 'abubakar_abdul_kader', null),
  ('abubakar_u12', 'abubakar', 'abubakar_jegaber_natchial', 'abubakar_khalibullah', null),
  ('abubakar_u13', 'abubakar', 'abubakar_farisha_begam', 'abubakar_muhammad_farhan', null),
  ('abubakar_u14', 'abubakar', 'abubakar_farhana_begam', 'abubakar_wassim_shah', null),
  ('abubakar_u15', 'abubakar', 'abubakar_faherah_begam', 'abubakar_thameem', null),
  ('abubakar_u16', 'abubakar', 'abubakar_abdul_razak', 'abubakar_ummu_salimah', null),
  ('abubakar_u17', 'abubakar', 'abubakar_riffeth_begam', 'abubakar_nasir_shah', null),
  ('abubakar_u18', 'abubakar', 'abubakar_rahima_begam', 'abubakar_hussain', null),
  ('abubakar_u19', 'abubakar', 'abubakar_mohammad_ridzwan', 'abubakar_thahmilla', null),
  ('abubakar_u20', 'abubakar', 'abubakar_jainabu_natchia', 'abubakar_harris', null),
  ('abubakar_u21', 'abubakar', 'abubakar_asina_begam', 'abubakar_gani_maricar', null),
  ('abubakar_u22', 'abubakar', 'abubakar_syed_janira_banu', 'abubakar_taj_mohammad', null),
  ('abubakar_u23', 'abubakar', 'abubakar_aminah_banu', 'abubakar_khalid', null),
  ('abubakar_u24', 'abubakar', 'abubakar_abu_bakar', 'abubakar_partner_of_abu_bakar', 'Abu Bakar''s second recorded marriage.'),
  ('abubakar_u25', 'abubakar', 'abubakar_jainalabuden', 'abubakar_partner_of_jainalabuden', null),
  ('abubakar_u26', 'abubakar', 'abubakar_samsunihar_aachama', 'abubakar_rafiq', null),
  ('abubakar_u27', 'abubakar', 'abubakar_farveen_banu', 'abubakar_ansari', null),
  ('abubakar_u28', 'abubakar', 'abubakar_ibrahim_fashith', 'abubakar_shireen', null),
  ('abubakar_u29', 'abubakar', 'abubakar_maimoon', 'abubakar_abdul_salam', null),
  ('abubakar_u30', 'abubakar', 'abubakar_faridah', 'abubakar_iqbal', null),
  ('abubakar_u31', 'abubakar', 'abubakar_yacob', 'abubakar_nur_nisha', null),
  ('abubakar_u32', 'abubakar', 'abubakar_mamudha', 'abubakar_dawood_sultan', null),
  ('abubakar_u33', 'abubakar', 'abubakar_mamudha', 'abubakar_salim', null)
on conflict (id) do update set
  partner1_id = excluded.partner1_id, partner2_id = excluded.partner2_id, note = excluded.note,
  updated_at = now();

-- ---------- abubakar : union_children ----------
delete from union_children where union_id like 'abubakar_u%';
insert into union_children (union_id, child_id, position) values
  ('abubakar_u1', 'abubakar_zubaidah', 0),
  ('abubakar_u1', 'abubakar_nisha', 1),
  ('abubakar_u1', 'abubakar_ali_saburi', 2),
  ('abubakar_u1', 'abubakar_mumtaj_begam', 3),
  ('abubakar_u2', 'abubakar_jahir_hussain', 0),
  ('abubakar_u2', 'abubakar_dawood', 1),
  ('abubakar_u2', 'abubakar_aisha_d_of_menatchia', 2),
  ('abubakar_u2', 'abubakar_nurjahan', 3),
  ('abubakar_u3', 'abubakar_irfan', 0),
  ('abubakar_u3', 'abubakar_farah', 1),
  ('abubakar_u6', 'abubakar_harsharth', 0),
  ('abubakar_u6', 'abubakar_ashraf', 1),
  ('abubakar_u7', 'abubakar_nasar', 0),
  ('abubakar_u7', 'abubakar_abu_bakar', 1),
  ('abubakar_u8', 'abubakar_abu_salee', 0),
  ('abubakar_u9', 'abubakar_hamidah', 0),
  ('abubakar_u10', 'abubakar_halimah_ummal', 0),
  ('abubakar_u10', 'abubakar_asina_begam', 1),
  ('abubakar_u11', 'abubakar_jegaber_natchial', 0),
  ('abubakar_u11', 'abubakar_abdul_razak', 1),
  ('abubakar_u11', 'abubakar_rahima_begam', 2),
  ('abubakar_u11', 'abubakar_jainabu_natchia', 3),
  ('abubakar_u12', 'abubakar_farisha_begam', 0),
  ('abubakar_u12', 'abubakar_farhana_begam', 1),
  ('abubakar_u12', 'abubakar_faherah_begam', 2),
  ('abubakar_u13', 'abubakar_muhammad', 0),
  ('abubakar_u13', 'abubakar_muhammad_fauz_khwaja', 1),
  ('abubakar_u14', 'abubakar_zayan_emir_shah', 0),
  ('abubakar_u16', 'abubakar_riffeth_begam', 0),
  ('abubakar_u16', 'abubakar_ayisha_raihana', 1),
  ('abubakar_u16', 'abubakar_shireen_halimah', 2),
  ('abubakar_u17', 'abubakar_khaira', 0),
  ('abubakar_u18', 'abubakar_mohammad_ridzwan', 0),
  ('abubakar_u18', 'abubakar_affrin_nisha', 1),
  ('abubakar_u19', 'abubakar_child_of_mohammad', 0),
  ('abubakar_u20', 'abubakar_haziqah', 0),
  ('abubakar_u21', 'abubakar_syed_janira_banu', 0),
  ('abubakar_u21', 'abubakar_aminah_banu', 1),
  ('abubakar_u22', 'abubakar_mohammad_farshith', 0),
  ('abubakar_u23', 'abubakar_mohamad_nadeem', 0),
  ('abubakar_u23', 'abubakar_mohamad_nabeel', 1),
  ('abubakar_u24', 'abubakar_jainalabuden', 0),
  ('abubakar_u24', 'abubakar_maimoon', 1),
  ('abubakar_u25', 'abubakar_samsunihar_aachama', 0),
  ('abubakar_u26', 'abubakar_farveen_banu', 0),
  ('abubakar_u26', 'abubakar_badhusha_raja', 1),
  ('abubakar_u27', 'abubakar_ibrahim_fashith', 0),
  ('abubakar_u27', 'abubakar_nafeelah', 1),
  ('abubakar_u27', 'abubakar_aadhil', 2),
  ('abubakar_u29', 'abubakar_faridah', 0),
  ('abubakar_u29', 'abubakar_yacob', 1),
  ('abubakar_u29', 'abubakar_mamudha', 2),
  ('abubakar_u30', 'abubakar_fajurullah', 0),
  ('abubakar_u30', 'abubakar_fauziah', 1),
  ('abubakar_u30', 'abubakar_riyaz', 2),
  ('abubakar_u31', 'abubakar_child_of_yacob', 0),
  ('abubakar_u31', 'abubakar_sibling_of_child_of_yacob', 1),
  ('abubakar_u31', 'abubakar_sibling_of_sibling_of_child_of_yacob', 2),
  ('abubakar_u32', 'abubakar_nisar', 0),
  ('abubakar_u32', 'abubakar_faizal', 1),
  ('abubakar_u32', 'abubakar_yassar', 2),
  ('abubakar_u32', 'abubakar_diwan', 3);

-- ---------- kuddus : people ----------
insert into people (id, family, name, gender, gen, title, traits, unknown, is_user) values
  ('kuddus_fatimah', 'kuddus', 'Fatimah', 'f', 1, null, null, false, false),
  ('kuddus_muhammad_kuddus', 'kuddus', 'Muhammad Kuddus', 'm', 1, null, 'A farmer in Sangamangalam, India, with one wife and four children.', false, false),
  ('kuddus_abdul_karim', 'kuddus', 'Abdul Karim', 'm', 2, null, null, false, false),
  ('kuddus_balqis', 'kuddus', 'Balqis', 'f', 2, null, '“To add on…” — details still being gathered.', false, false),
  ('kuddus_bavamaideen_thadi_vappa', 'kuddus', 'Bavamaideen Thadi Vappa', 'm', 2, '“Thadi Vappa”', 'Known for his long white beard — thadi means beard in Tamil.', false, false),
  ('kuddus_ghazali', 'kuddus', 'Ghazali', 'm', 2, null, null, false, false),
  ('kuddus_partner_of_abdul_karim', 'kuddus', 'Partner of Abdul Karim', 'f', 2, null, null, true, false),
  ('kuddus_zaithun', 'kuddus', 'Zaithun', 'f', 2, null, null, false, false),
  ('kuddus_abu', 'kuddus', 'Abu', 'm', 3, null, null, false, false),
  ('kuddus_anwar', 'kuddus', 'Anwar', 'm', 3, null, null, false, false),
  ('kuddus_basheera_sellama_machi', 'kuddus', 'Basheera Sellama Machi', 'f', 3, null, null, false, false),
  ('kuddus_fairoz', 'kuddus', 'Fairoz', 'm', 3, null, null, false, false),
  ('kuddus_father_of_sujana', 'kuddus', 'Father of Sujana', 'm', 3, null, null, true, false),
  ('kuddus_haja', 'kuddus', 'Haja', 'm', 3, null, null, false, false),
  ('kuddus_najumudeen', 'kuddus', 'Najumudeen', 'm', 3, null, null, false, false),
  ('kuddus_partner_of_anwar', 'kuddus', 'Partner of Anwar', 'f', 3, null, null, true, false),
  ('kuddus_partner_of_fairoz', 'kuddus', 'Partner of Fairoz', 'f', 3, null, null, true, false),
  ('kuddus_siraj', 'kuddus', 'Siraj', 'm', 3, null, null, false, false),
  ('kuddus_son_of_balqis', 'kuddus', 'Son of Balqis', 'm', 3, null, null, true, false),
  ('kuddus_son_of_balqis_2', 'kuddus', 'Son of Balqis (2)', 'm', 3, null, null, true, false),
  ('kuddus_zeenath_aachi', 'kuddus', 'Zeenath Aachi', 'f', 3, null, null, false, false),
  ('kuddus_aisha_farhana', 'kuddus', 'Aisha Farhana', 'f', 4, null, null, false, false),
  ('kuddus_brother_of_sujana', 'kuddus', 'Brother of Sujana', 'm', 4, null, null, true, false),
  ('kuddus_daughter_of_anwar', 'kuddus', 'Daughter of Anwar', 'f', 4, null, null, true, false),
  ('kuddus_daughter_of_fairoz', 'kuddus', 'Daughter of Fairoz', 'f', 4, null, null, true, false),
  ('kuddus_nur_faaliha', 'kuddus', 'Nur Faaliha', 'f', 4, null, null, false, false),
  ('kuddus_salmaan', 'kuddus', 'Salmaan', 'm', 4, null, null, false, false),
  ('kuddus_sheik', 'kuddus', 'Sheik', 'm', 4, null, null, false, false),
  ('kuddus_sister_of_daughter_of_fairoz', 'kuddus', 'Sister of Daughter of Fairoz', 'f', 4, null, null, true, false),
  ('kuddus_son_of_basheera', 'kuddus', 'Son of Basheera', 'm', 4, null, null, true, false),
  ('kuddus_sujana', 'kuddus', 'Sujana', 'f', 4, null, null, false, false),
  ('kuddus_thasneem', 'kuddus', 'Thasneem', 'f', 4, null, null, false, false),
  ('kuddus_yara', 'kuddus', 'Yara', 'f', 5, null, null, false, false),
  ('kuddus_zeeya', 'kuddus', 'Ziya', 'f', 5, null, null, false, false),
  ('kuddus_waqas', 'kuddus', 'Waqas', 'm', 5, null, null, false, false),
  ('kuddus_danial', 'kuddus', 'Danial', 'm', 5, null, null, false, false)
on conflict (id) do update set
  family = excluded.family, name = excluded.name, gender = excluded.gender, gen = excluded.gen,
  title = excluded.title, traits = excluded.traits, unknown = excluded.unknown, is_user = excluded.is_user,
  updated_at = now();

-- ---------- kuddus : unions ----------
insert into unions (id, family, partner1_id, partner2_id, note) values
  ('kuddus_u1', 'kuddus', 'kuddus_fatimah', 'kuddus_muhammad_kuddus', 'Fatimah and Muhammad Kuddus are the founding couple of the Kuddus line.'),
  ('kuddus_u2', 'kuddus', 'kuddus_bavamaideen_thadi_vappa', 'kuddus_zaithun', null),
  ('kuddus_u3', 'kuddus', 'kuddus_zeenath_aachi', 'kuddus_najumudeen', null),
  ('kuddus_u4', 'kuddus', 'kuddus_aisha_farhana', 'kuddus_sheik', null),
  ('kuddus_u5', 'kuddus', 'kuddus_salmaan', 'kuddus_thasneem', null),
  ('kuddus_u6', 'kuddus', 'kuddus_anwar', 'kuddus_partner_of_anwar', null),
  ('kuddus_u7', 'kuddus', 'kuddus_abdul_karim', 'kuddus_partner_of_abdul_karim', null),
  ('kuddus_u8', 'kuddus', 'kuddus_fairoz', 'kuddus_partner_of_fairoz', null),
  ('kuddus_u9', 'kuddus', 'kuddus_balqis', 'kuddus_ghazali', null),
  ('kuddus_u10', 'kuddus', 'kuddus_basheera_sellama_machi', 'kuddus_father_of_sujana', null)
on conflict (id) do update set
  partner1_id = excluded.partner1_id, partner2_id = excluded.partner2_id, note = excluded.note,
  updated_at = now();

-- ---------- kuddus : union_children ----------
delete from union_children where union_id like 'kuddus_u%';
insert into union_children (union_id, child_id, position) values
  ('kuddus_u1', 'kuddus_bavamaideen_thadi_vappa', 0),
  ('kuddus_u1', 'kuddus_abdul_karim', 1),
  ('kuddus_u1', 'kuddus_balqis', 2),
  ('kuddus_u2', 'kuddus_zeenath_aachi', 0),
  ('kuddus_u2', 'kuddus_anwar', 1),
  ('kuddus_u3', 'kuddus_aisha_farhana', 0),
  ('kuddus_u3', 'kuddus_salmaan', 1),
  ('kuddus_u3', 'kuddus_nur_faaliha', 2),
  ('kuddus_u4', 'kuddus_zeeya', 0),
  ('kuddus_u4', 'kuddus_yara', 1),
  ('kuddus_u4', 'kuddus_waqas', 2),
  ('kuddus_u5', 'kuddus_danial', 0),
  ('kuddus_u6', 'kuddus_daughter_of_anwar', 0),
  ('kuddus_u7', 'kuddus_fairoz', 0),
  ('kuddus_u7', 'kuddus_siraj', 1),
  ('kuddus_u8', 'kuddus_daughter_of_fairoz', 0),
  ('kuddus_u8', 'kuddus_sister_of_daughter_of_fairoz', 1),
  ('kuddus_u9', 'kuddus_haja', 0),
  ('kuddus_u9', 'kuddus_abu', 1),
  ('kuddus_u9', 'kuddus_son_of_balqis', 2),
  ('kuddus_u9', 'kuddus_son_of_balqis_2', 3),
  ('kuddus_u9', 'kuddus_basheera_sellama_machi', 4),
  ('kuddus_u10', 'kuddus_sujana', 0),
  ('kuddus_u10', 'kuddus_brother_of_sujana', 1),
  ('kuddus_u10', 'kuddus_son_of_basheera', 2);

-- ---------- maricar : people ----------
insert into people (id, family, name, gender, gen, title, traits, unknown, is_user) values
  ('maricar_alimah', 'maricar', 'Alimah', 'f', 1, null, null, false, false),
  ('maricar_vacha', 'maricar', 'Vacha', 'm', 1, null, null, false, false),
  ('maricar_amina', 'maricar', 'Amina', 'f', 2, null, 'Passed away shortly after her second child was born. Her mother Alimah''s brother was a Governor in Japan in 1935.', false, false),
  ('maricar_partner_of_sultan_maricar', 'maricar', 'Partner of Sultan Maricar', 'f', 2, null, null, true, false),
  ('maricar_sultan_maricar', 'maricar', 'Sultan Maricar', 'm', 2, null, 'Half-Malay businessman; ran a printing shop on Joo Chiat Road, Singapore, then a floral business in Karikal, India.', false, false),
  ('maricar_abdulrahim', 'maricar', 'AbdulRahim', 'm', 3, null, null, false, false),
  ('maricar_aisha_natchia_ummanama', 'maricar', 'Aisha Natchia (Ummanama)', 'f', 3, '“Ummanama”', 'Had several children together with wide-reaching descendants across the Maricar line.', false, false),
  ('maricar_fauziah', 'maricar', 'Fauziah', 'f', 3, null, null, false, false),
  ('maricar_haijah', 'maricar', 'Haijah', 'f', 3, null, null, false, false),
  ('maricar_hamid', 'maricar', 'Hamid', 'm', 3, null, null, false, false),
  ('maricar_hamid_maami', 'maricar', 'Hamid Maami', 'f', 3, null, 'Married Sheikh Dawood.', false, false),
  ('maricar_latha_amma', 'maricar', 'Latha Amma', 'f', 3, null, null, false, false),
  ('maricar_maideen', 'maricar', 'Maideen', 'm', 3, null, 'Amina''s brother — one of several marriages linking the two branches of the family.', false, false),
  ('maricar_mother_of_daughter_of_sarebu', 'maricar', 'Mother of Daughter of Sarebu', 'f', 3, null, null, true, false),
  ('maricar_partner_of_abdulrahim', 'maricar', 'Partner of AbdulRahim', 'f', 3, null, null, true, false),
  ('maricar_partner_of_aisha_natchia', 'maricar', 'Partner of Aisha Natchia', 'm', 3, null, null, true, false),
  ('maricar_partner_of_haijah', 'maricar', 'Partner of Haijah', 'm', 3, null, null, true, false),
  ('maricar_sarebu', 'maricar', 'Sarebu', 'm', 3, null, null, false, false),
  ('maricar_sheikh_dawood', 'maricar', 'Sheikh Dawood', 'm', 3, null, null, false, false),
  ('maricar_aachikani_maami', 'maricar', 'Aachikani Maami', 'f', 4, null, null, false, false),
  ('maricar_arief', 'maricar', 'Arief', 'm', 4, null, null, false, false),
  ('maricar_banu', 'maricar', 'Banu', 'f', 4, null, null, false, false),
  ('maricar_child_of_abdulrahim', 'maricar', 'Child of AbdulRahim', 'u', 4, null, null, true, false),
  ('maricar_child_of_abdulrahim_2', 'maricar', 'Child of AbdulRahim (2)', 'u', 4, null, null, true, false),
  ('maricar_daughter_of_sarebu', 'maricar', 'Daughter of Sarebu', 'f', 4, null, null, true, false),
  ('maricar_fareedha', 'maricar', 'Fareedha', 'f', 4, null, null, false, false),
  ('maricar_father_of_anis', 'maricar', 'Father of Anis', 'm', 4, null, null, true, false),
  ('maricar_father_of_aslam', 'maricar', 'Father of Aslam', 'm', 4, null, null, true, false),
  ('maricar_father_of_daughter_of_thangam', 'maricar', 'Father of Daughter of Thangam', 'm', 4, null, null, true, false),
  ('maricar_father_of_farvin', 'maricar', 'Father of Farvin', 'm', 4, null, null, true, false),
  ('maricar_father_of_son_of_jareena', 'maricar', 'Father of Son of Jareena', 'm', 4, null, null, true, false),
  ('maricar_hilal', 'maricar', 'Hilal', 'm', 4, null, null, false, false),
  ('maricar_ibrahim', 'maricar', 'Ibrahim', 'm', 4, null, null, false, false),
  ('maricar_jareena_muthu', 'maricar', 'Jareena Muthu', 'f', 4, null, null, false, false),
  ('maricar_mother_of_shamima', 'maricar', 'Mother of Shamima', 'f', 4, null, null, true, false),
  ('maricar_muthu_vappa', 'maricar', 'Muthu Vappa', 'm', 4, null, 'His large family of seven children.', false, false),
  ('maricar_partner_of_muthu', 'maricar', 'Partner of Muthu', 'f', 4, null, null, true, false),
  ('maricar_ponnachi', 'maricar', 'Ponnachi', 'f', 4, null, 'Linked into this family tree twice over, through two different marriages.', false, false),
  ('maricar_saramma', 'maricar', 'Saramma', 'f', 4, null, null, false, false),
  ('maricar_sellakani_mami', 'maricar', 'Sellakani Mami', 'f', 4, null, null, false, false),
  ('maricar_setha_vappa', 'maricar', 'Setha Vappa', 'm', 4, null, 'Married his cousin Saramma.', false, false),
  ('maricar_settu_vaapa', 'maricar', 'Settu Vaapa', 'm', 4, null, null, false, false),
  ('maricar_sister_of_daughter_of_sarebu', 'maricar', 'Sister of Daughter of Sarebu', 'f', 4, null, null, true, false),
  ('maricar_sister_of_hilal', 'maricar', 'Sister of Hilal', 'f', 4, null, null, true, false),
  ('maricar_son_of_haijah', 'maricar', 'Son of Haijah', 'm', 4, null, null, true, false),
  ('maricar_son_of_haijah_2', 'maricar', 'Son of Haijah (2)', 'm', 4, null, null, true, false),
  ('maricar_thanga', 'maricar', 'Thanga', 'f', 4, null, null, false, false),
  ('maricar_thangam', 'maricar', 'Thangam', 'f', 4, null, null, false, false),
  ('maricar_udhumalai_vaapa', 'maricar', 'Udhumalai Vaapa', 'm', 4, null, 'Aisha Natchia''s grandson-in-law — married Fareedha, from the 1st-wife line.', false, false),
  ('maricar_anis', 'maricar', 'Anis', 'f', 5, null, null, false, false),
  ('maricar_aslam', 'maricar', 'Aslam', 'm', 5, null, null, false, false),
  ('maricar_asmamama', 'maricar', 'Asmamama', 'f', 5, null, null, false, false),
  ('maricar_banu_2', 'maricar', 'Banu (2)', 'f', 5, null, null, false, false),
  ('maricar_brother_of_son_of_jareena', 'maricar', 'Brother of Son of Jareena', 'm', 5, null, null, true, false),
  ('maricar_daughter_of_muthu', 'maricar', 'Daughter of Muthu', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_muthu_2', 'maricar', 'Daughter of Muthu (2)', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_muthu_3', 'maricar', 'Daughter of Muthu (3)', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_muthu_4', 'maricar', 'Daughter of Muthu (4)', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_partner_of_muthu', 'maricar', 'Daughter of Partner of Muthu', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_partner_of_muthu_2', 'maricar', 'Daughter of Partner of Muthu (2)', 'f', 5, null, null, true, false),
  ('maricar_daughter_of_thangam', 'maricar', 'Daughter of Thangam', 'f', 5, null, null, true, false),
  ('maricar_fahima', 'maricar', 'Fahima', 'f', 5, null, null, false, false),
  ('maricar_farhana', 'maricar', 'Farhana', 'f', 5, null, null, false, false),
  ('maricar_farvin', 'maricar', 'Farvin', 'f', 5, null, null, false, false),
  ('maricar_father_of_jafir', 'maricar', 'Father of Jafir', 'm', 5, null, null, true, false),
  ('maricar_father_of_muhsinah', 'maricar', 'Father of Muhsinah', 'm', 5, null, null, true, false),
  ('maricar_jaani', 'maricar', 'Jaani', 'f', 5, null, null, false, false),
  ('maricar_jinnah', 'maricar', 'Jinnah', 'f', 5, null, null, false, false),
  ('maricar_kamilah', 'maricar', 'Kamilah', 'f', 5, null, null, false, false),
  ('maricar_late_partner_of_asmamama', 'maricar', 'Late partner of Asmamama', 'm', 5, null, null, true, false),
  ('maricar_mother_of_son_of_navaz', 'maricar', 'Mother of Son of Navaz', 'f', 5, null, null, true, false),
  ('maricar_naasik', 'maricar', 'Naasik', 'm', 5, null, null, false, false),
  ('maricar_navaz', 'maricar', 'Navaz', 'm', 5, null, null, false, false),
  ('maricar_nawaz', 'maricar', 'Nawaz', 'm', 5, null, null, false, false),
  ('maricar_nizam', 'maricar', 'Nizam', 'm', 5, null, null, false, false),
  ('maricar_nizarah', 'maricar', 'Nizarah', 'f', 5, null, null, false, false),
  ('maricar_omar', 'maricar', 'Omar', 'm', 5, null, null, false, false),
  ('maricar_partner_of_naasik', 'maricar', 'Partner of Naasik', 'f', 5, null, null, true, false),
  ('maricar_partner_of_nizam', 'maricar', 'Partner of Nizam', 'f', 5, null, null, true, false),
  ('maricar_partner_of_sellapapa', 'maricar', 'Partner of SellaPapa', 'm', 5, null, null, true, false),
  ('maricar_partner_of_setha', 'maricar', 'Partner of Setha', 'm', 5, null, null, true, false),
  ('maricar_partner_of_siraj', 'maricar', 'Partner of Siraj', 'f', 5, null, null, true, false),
  ('maricar_rafeeq', 'maricar', 'Rafeeq', 'm', 5, null, null, false, false),
  ('maricar_raja', 'maricar', 'Raja', 'm', 5, null, null, false, false),
  ('maricar_ramli', 'maricar', 'Ramli', 'm', 5, null, null, false, false),
  ('maricar_rosy', 'maricar', 'Rosy', 'f', 5, null, null, false, false),
  ('maricar_said_mubarak', 'maricar', 'Said Mubarak', 'm', 5, null, null, false, false),
  ('maricar_sellapapa', 'maricar', 'SellaPapa', 'f', 5, null, null, false, false),
  ('maricar_setha_munnai', 'maricar', 'Setha Munnai', 'f', 5, null, null, false, false),
  ('maricar_shakila', 'maricar', 'Shakila', 'f', 5, null, null, false, false),
  ('maricar_shamima', 'maricar', 'Shamima', 'f', 5, null, null, false, false),
  ('maricar_siraj_2', 'maricar', 'Siraj (2)', 'm', 5, null, null, false, false),
  ('maricar_son_of_jareena', 'maricar', 'Son of Jareena', 'm', 5, null, null, true, false),
  ('maricar_son_of_muthu', 'maricar', 'Son of Muthu', 'm', 5, null, null, true, false),
  ('maricar_zubaidah_2', 'maricar', 'Zubaidah (2)', 'f', 5, null, null, false, false),
  ('maricar_brother_of_daughter_of_sellapapa', 'maricar', 'Brother of Daughter of SellaPapa', 'm', 6, null, null, true, false),
  ('maricar_brother_of_kuluthu', 'maricar', 'Brother of Kuluthu', 'm', 6, null, null, true, false),
  ('maricar_brother_of_sister_of_salmaan', 'maricar', 'Brother of Sister of Salmaan', 'm', 6, null, null, true, false),
  ('maricar_daughter_of_banu', 'maricar', 'Daughter of Banu', 'f', 6, null, null, true, false),
  ('maricar_daughter_of_nizam', 'maricar', 'Daughter of Nizam', 'f', 6, null, null, true, false),
  ('maricar_daughter_of_sellapapa', 'maricar', 'Daughter of SellaPapa', 'f', 6, null, null, true, false),
  ('maricar_daughter_of_siraj', 'maricar', 'Daughter of Siraj', 'f', 6, null, null, true, false),
  ('maricar_jafir', 'maricar', 'Jafir', 'm', 6, null, null, false, false),
  ('maricar_jinnah_2', 'maricar', 'Jinnah (2)', 'm', 6, null, null, false, false),
  ('maricar_kuluthu', 'maricar', 'Kuluthu', 'f', 6, null, null, false, false),
  ('maricar_liyana', 'maricar', 'Liyana', 'f', 6, null, null, false, false),
  ('maricar_muhadir', 'maricar', 'Muhadir', 'm', 6, null, null, false, false),
  ('maricar_muhsinah', 'maricar', 'Muhsinah', 'f', 6, null, null, false, false),
  ('maricar_nawsath', 'maricar', 'Nawsath', 'f', 6, null, null, false, false),
  ('maricar_partner_of_jafir', 'maricar', 'Partner of Jafir', 'f', 6, null, null, true, false),
  ('maricar_partner_of_sitima', 'maricar', 'Partner of Sitima', 'm', 6, null, null, true, false),
  ('maricar_salmaan', 'maricar', 'Salmaan', 'm', 6, null, null, false, false),
  ('maricar_sister_of_muhadir', 'maricar', 'Sister of Muhadir', 'f', 6, null, null, true, false),
  ('maricar_sister_of_salmaan', 'maricar', 'Sister of Salmaan', 'f', 6, null, null, true, false),
  ('maricar_sister_of_sister_of_salmaan', 'maricar', 'Sister of Sister of Salmaan', 'f', 6, null, null, true, false),
  ('maricar_sitima', 'maricar', 'Sitima', 'f', 6, null, null, false, false),
  ('maricar_son_of_naasik', 'maricar', 'Son of Naasik', 'm', 6, null, null, true, false),
  ('maricar_son_of_naasik_2', 'maricar', 'Son of Naasik (2)', 'm', 6, null, null, true, false),
  ('maricar_son_of_navaz', 'maricar', 'Son of Navaz', 'm', 6, null, null, true, false),
  ('maricar_son_of_raja', 'maricar', 'Son of Raja', 'm', 6, null, null, true, false),
  ('maricar_son_of_raja_2', 'maricar', 'Son of Raja (2)', 'm', 6, null, null, true, false),
  ('maricar_son_of_siraj', 'maricar', 'Son of Siraj', 'm', 6, null, null, true, false),
  ('maricar_son_of_siraj_2', 'maricar', 'Son of Siraj (2)', 'm', 6, null, null, true, false),
  ('maricar_ashraf_2', 'maricar', 'Ashraf (2)', 'm', 7, null, null, false, false),
  ('maricar_brother_of_ashraf', 'maricar', 'Brother of Ashraf', 'm', 7, null, null, true, false),
  ('maricar_brother_of_juwairiah', 'maricar', 'Brother of Juwairiah', 'm', 7, null, null, true, false),
  ('maricar_juwairiah', 'maricar', 'Juwairiah', 'f', 7, null, null, false, false),
  ('maricar_mujeeb', 'maricar', 'Mujeeb', 'm', 7, null, null, false, false),
  ('maricar_sister_of_brother_of_ashraf', 'maricar', 'Sister of Brother of Ashraf', 'f', 7, null, null, true, false),
  ('maricar_son_of_jafir', 'maricar', 'Son of Jafir', 'm', 7, null, null, true, false)
on conflict (id) do update set
  family = excluded.family, name = excluded.name, gender = excluded.gender, gen = excluded.gen,
  title = excluded.title, traits = excluded.traits, unknown = excluded.unknown, is_user = excluded.is_user,
  updated_at = now();

-- ---------- maricar : unions ----------
insert into unions (id, family, partner1_id, partner2_id, note) values
  ('maricar_u1', 'maricar', 'maricar_alimah', 'maricar_vacha', null),
  ('maricar_u2', 'maricar', 'maricar_amina', 'maricar_sultan_maricar', 'Amina and Sultan Maricar are the founding couple of the Maricar line.'),
  ('maricar_u3', 'maricar', 'maricar_hamid_maami', 'maricar_sheikh_dawood', null),
  ('maricar_u4', 'maricar', 'maricar_jareena_muthu', 'maricar_father_of_son_of_jareena', null),
  ('maricar_u5', 'maricar', 'maricar_banu', 'maricar_father_of_aslam', null),
  ('maricar_u6', 'maricar', 'maricar_thangam', 'maricar_father_of_daughter_of_thangam', null),
  ('maricar_u7', 'maricar', 'maricar_sultan_maricar', 'maricar_partner_of_sultan_maricar', null),
  ('maricar_u8', 'maricar', 'maricar_sarebu', 'maricar_mother_of_daughter_of_sarebu', null),
  ('maricar_u9', 'maricar', 'maricar_latha_amma', 'maricar_maideen', null),
  ('maricar_u10', 'maricar', 'maricar_ponnachi', 'maricar_ibrahim', null),
  ('maricar_u11', 'maricar', 'maricar_mother_of_son_of_navaz', 'maricar_navaz', null),
  ('maricar_u12', 'maricar', 'maricar_fareedha', 'maricar_udhumalai_vaapa', null),
  ('maricar_u13', 'maricar', 'maricar_jaani', 'maricar_father_of_muhsinah', null),
  ('maricar_u14', 'maricar', 'maricar_partner_of_naasik', 'maricar_naasik', null),
  ('maricar_u15', 'maricar', 'maricar_partner_of_nizam', 'maricar_nizam', null),
  ('maricar_u16', 'maricar', 'maricar_hamid', 'maricar_fauziah', null),
  ('maricar_u17', 'maricar', 'maricar_haijah', 'maricar_partner_of_haijah', null),
  ('maricar_u18', 'maricar', 'maricar_partner_of_abdulrahim', 'maricar_abdulrahim', null),
  ('maricar_u19', 'maricar', 'maricar_aisha_natchia_ummanama', 'maricar_partner_of_aisha_natchia', null),
  ('maricar_u20', 'maricar', 'maricar_muthu_vappa', 'maricar_partner_of_muthu', null),
  ('maricar_u21', 'maricar', 'maricar_thanga', 'maricar_arief', null),
  ('maricar_u22', 'maricar', 'maricar_sellakani_mami', 'maricar_father_of_farvin', null),
  ('maricar_u23', 'maricar', 'maricar_farvin', 'maricar_said_mubarak', null),
  ('maricar_u24', 'maricar', 'maricar_sellapapa', 'maricar_partner_of_sellapapa', null),
  ('maricar_u25', 'maricar', 'maricar_setha_munnai', 'maricar_partner_of_setha', null),
  ('maricar_u26', 'maricar', 'maricar_saramma', 'maricar_setha_vappa', null),
  ('maricar_u27', 'maricar', 'maricar_banu_2', 'maricar_father_of_jafir', null),
  ('maricar_u28', 'maricar', 'maricar_jafir', 'maricar_partner_of_jafir', null),
  ('maricar_u29', 'maricar', 'maricar_siraj_2', 'maricar_partner_of_siraj', null),
  ('maricar_u30', 'maricar', 'maricar_raja', 'maricar_farhana', null),
  ('maricar_u31', 'maricar', 'maricar_aachikani_maami', 'maricar_father_of_anis', null),
  ('maricar_u32', 'maricar', 'maricar_anis', 'maricar_ramli', null),
  ('maricar_u33', 'maricar', 'maricar_nawsath', 'maricar_jinnah_2', null),
  ('maricar_u34', 'maricar', 'maricar_mother_of_shamima', 'maricar_settu_vaapa', null),
  ('maricar_u35', 'maricar', 'maricar_asmamama', 'maricar_late_partner_of_asmamama', null),
  ('maricar_u36', 'maricar', 'maricar_sitima', 'maricar_partner_of_sitima', null)
on conflict (id) do update set
  partner1_id = excluded.partner1_id, partner2_id = excluded.partner2_id, note = excluded.note,
  updated_at = now();

-- ---------- maricar : union_children ----------
delete from union_children where union_id like 'maricar_u%';
insert into union_children (union_id, child_id, position) values
  ('maricar_u1', 'maricar_amina', 0),
  ('maricar_u2', 'maricar_hamid_maami', 0),
  ('maricar_u3', 'maricar_jareena_muthu', 0),
  ('maricar_u3', 'maricar_banu', 1),
  ('maricar_u3', 'maricar_thangam', 2),
  ('maricar_u4', 'maricar_son_of_jareena', 0),
  ('maricar_u4', 'maricar_brother_of_son_of_jareena', 1),
  ('maricar_u5', 'maricar_aslam', 0),
  ('maricar_u5', 'maricar_fahima', 1),
  ('maricar_u6', 'maricar_daughter_of_thangam', 0),
  ('maricar_u7', 'maricar_sarebu', 0),
  ('maricar_u7', 'maricar_latha_amma', 1),
  ('maricar_u7', 'maricar_fauziah', 2),
  ('maricar_u7', 'maricar_haijah', 3),
  ('maricar_u7', 'maricar_abdulrahim', 4),
  ('maricar_u7', 'maricar_aisha_natchia_ummanama', 5),
  ('maricar_u8', 'maricar_daughter_of_sarebu', 0),
  ('maricar_u8', 'maricar_sister_of_daughter_of_sarebu', 1),
  ('maricar_u9', 'maricar_ponnachi', 0),
  ('maricar_u9', 'maricar_fareedha', 1),
  ('maricar_u10', 'maricar_mother_of_son_of_navaz', 0),
  ('maricar_u11', 'maricar_son_of_navaz', 0),
  ('maricar_u12', 'maricar_jaani', 0),
  ('maricar_u12', 'maricar_partner_of_naasik', 1),
  ('maricar_u12', 'maricar_partner_of_nizam', 2),
  ('maricar_u13', 'maricar_muhsinah', 0),
  ('maricar_u13', 'maricar_muhadir', 1),
  ('maricar_u13', 'maricar_sister_of_muhadir', 2),
  ('maricar_u14', 'maricar_son_of_naasik', 0),
  ('maricar_u14', 'maricar_son_of_naasik_2', 1),
  ('maricar_u15', 'maricar_daughter_of_nizam', 0),
  ('maricar_u16', 'maricar_hilal', 0),
  ('maricar_u16', 'maricar_sister_of_hilal', 1),
  ('maricar_u17', 'maricar_son_of_haijah', 0),
  ('maricar_u17', 'maricar_son_of_haijah_2', 1),
  ('maricar_u18', 'maricar_child_of_abdulrahim', 0),
  ('maricar_u18', 'maricar_child_of_abdulrahim_2', 1),
  ('maricar_u19', 'maricar_muthu_vappa', 0),
  ('maricar_u19', 'maricar_thanga', 1),
  ('maricar_u19', 'maricar_sellakani_mami', 2),
  ('maricar_u19', 'maricar_saramma', 3),
  ('maricar_u19', 'maricar_aachikani_maami', 4),
  ('maricar_u19', 'maricar_mother_of_shamima', 5),
  ('maricar_u20', 'maricar_son_of_muthu', 0),
  ('maricar_u20', 'maricar_daughter_of_muthu', 1),
  ('maricar_u20', 'maricar_daughter_of_partner_of_muthu', 2),
  ('maricar_u20', 'maricar_daughter_of_muthu_2', 3),
  ('maricar_u20', 'maricar_daughter_of_muthu_3', 4),
  ('maricar_u20', 'maricar_daughter_of_partner_of_muthu_2', 5),
  ('maricar_u20', 'maricar_daughter_of_muthu_4', 6),
  ('maricar_u21', 'maricar_rafeeq', 0),
  ('maricar_u21', 'maricar_jinnah', 1),
  ('maricar_u21', 'maricar_omar', 2),
  ('maricar_u21', 'maricar_nawaz', 3),
  ('maricar_u21', 'maricar_kamilah', 4),
  ('maricar_u21', 'maricar_rosy', 5),
  ('maricar_u21', 'maricar_nizarah', 6),
  ('maricar_u22', 'maricar_farvin', 0),
  ('maricar_u22', 'maricar_sellapapa', 1),
  ('maricar_u22', 'maricar_setha_munnai', 2),
  ('maricar_u23', 'maricar_salmaan', 0),
  ('maricar_u23', 'maricar_sister_of_salmaan', 1),
  ('maricar_u23', 'maricar_sister_of_sister_of_salmaan', 2),
  ('maricar_u23', 'maricar_brother_of_sister_of_salmaan', 3),
  ('maricar_u24', 'maricar_daughter_of_sellapapa', 0),
  ('maricar_u24', 'maricar_brother_of_daughter_of_sellapapa', 1),
  ('maricar_u25', 'maricar_kuluthu', 0),
  ('maricar_u25', 'maricar_brother_of_kuluthu', 1),
  ('maricar_u26', 'maricar_banu_2', 0),
  ('maricar_u26', 'maricar_siraj_2', 1),
  ('maricar_u26', 'maricar_raja', 2),
  ('maricar_u27', 'maricar_jafir', 0),
  ('maricar_u27', 'maricar_daughter_of_banu', 1),
  ('maricar_u28', 'maricar_son_of_jafir', 0),
  ('maricar_u29', 'maricar_son_of_siraj', 0),
  ('maricar_u29', 'maricar_son_of_siraj_2', 1),
  ('maricar_u29', 'maricar_daughter_of_siraj', 2),
  ('maricar_u30', 'maricar_son_of_raja', 0),
  ('maricar_u30', 'maricar_son_of_raja_2', 1),
  ('maricar_u31', 'maricar_anis', 0),
  ('maricar_u32', 'maricar_liyana', 0),
  ('maricar_u33', 'maricar_juwairiah', 0),
  ('maricar_u33', 'maricar_brother_of_juwairiah', 1),
  ('maricar_u34', 'maricar_shamima', 0),
  ('maricar_u34', 'maricar_shakila', 1),
  ('maricar_u34', 'maricar_zubaidah_2', 2),
  ('maricar_u34', 'maricar_asmamama', 3),
  ('maricar_u35', 'maricar_sitima', 0),
  ('maricar_u36', 'maricar_mujeeb', 0),
  ('maricar_u36', 'maricar_ashraf_2', 1),
  ('maricar_u36', 'maricar_brother_of_ashraf', 2),
  ('maricar_u36', 'maricar_sister_of_brother_of_ashraf', 3);

